-- ============================================================
-- NCR-OMS bulk order-history import
-- Generated by Claude (Anthropic) for: Meesho, Flipkart, Amazon,
-- Snapdeal, Myntra "DOMESTIC_ORDER_DATA_2026-27" exports.
-- Rows: 4119 orders / 4695 items / 4119 shipments / 80 returns
--
-- RUN THE FILES IN THIS DIRECTORY IN FILENAME ORDER (00_..., 01_..., ...,
-- 99_finalize.sql last) -- each one is small enough for the Supabase SQL
-- editor. Every file is independently safe to re-run if something fails
-- partway; re-running the whole sequence never duplicates data.
--
-- READ BEFORE RUNNING (also see the chat write-up / project doc for full detail):
--  1. Brand/company is resolved per order from product-title text.
--     Orders with no reliable signal (all of Meesho, most of Amazon,
--     a handful of Flipkart/Snapdeal) go under a 4th pseudo-company
--     "UNASSIGNED - NEEDS BRAND REVIEW" rather than being guessed.
--     See the review queries in 99_finalize.sql to reassign them.
--  2. No inventory_ledger stock-reservation rows are written for this
--     historical backfill (these orders already happened; reserving
--     stock against them would send on-hand deeply negative). If you
--     want current on-hand stock to reflect a starting point, use the
--     Company & Setup / Party Master "Stock In" flow for an opening
--     balance instead.
--  3. marketplace_accounts created here get a PLACEHOLDER encrypted
--     credentials blob (this script has no access to the live
--     ENCRYPTION_MASTER_KEY) - fine for CSV-history, but re-enter
--     real credentials via Company & Setup before using any live
--     marketplace API connector on these accounts.
--  4. Staging tables are prefixed _import_stg_ and are left in place
--     after 99_finalize.sql runs (harmless) -- drop them yourself
--     whenever convenient, see the commented-out DROP block at the
--     bottom of 99_finalize.sql.
-- ============================================================

BEGIN;

-- Auto-assign memory: a SKU code we've resolved with confidence once
-- (from a product title mentioning the brand) is remembered here, so a
-- future import of the same code does not need to ask again.
CREATE TABLE IF NOT EXISTS import_brand_hints (
  id serial PRIMARY KEY,
  marketplace_sku varchar(200) NOT NULL,
  brand_name varchar(150) NOT NULL,
  company_legal_name varchar(200) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(marketplace_sku, brand_name)
);

-- Ensure the 3 real companies + the review-queue pseudo-company exist.
-- (matches scripts/seed-companies.ts legalNames exactly where real)
DO $$
DECLARE
  v_company_id integer;
  v_brand_id integer;
  v_wh_id integer;
BEGIN
  -- NYKO_MART
  SELECT id INTO v_company_id FROM companies WHERE legal_name = 'Nyko Mart' LIMIT 1;
  IF v_company_id IS NULL THEN
    INSERT INTO companies (legal_name, display_name) VALUES ('Nyko Mart', 'NYKO MART') RETURNING id INTO v_company_id;
  END IF;
  SELECT id INTO v_brand_id FROM brands WHERE company_id = v_company_id AND name = 'Vardhamati' LIMIT 1;
  IF v_brand_id IS NULL THEN
    INSERT INTO brands (company_id, name) VALUES (v_company_id, 'Vardhamati') RETURNING id INTO v_brand_id;
  END IF;
  SELECT id INTO v_wh_id FROM warehouses WHERE company_id = v_company_id AND is_default = true LIMIT 1;
  IF v_wh_id IS NULL THEN
    INSERT INTO warehouses (company_id, name, is_default) VALUES (v_company_id, 'Default Warehouse', true);
  END IF;

  -- RUGARA
  SELECT id INTO v_company_id FROM companies WHERE legal_name = 'Rugara' LIMIT 1;
  IF v_company_id IS NULL THEN
    INSERT INTO companies (legal_name, display_name) VALUES ('Rugara', 'RUGARA') RETURNING id INTO v_company_id;
  END IF;
  SELECT id INTO v_brand_id FROM brands WHERE company_id = v_company_id AND name = 'Arvagam' LIMIT 1;
  IF v_brand_id IS NULL THEN
    INSERT INTO brands (company_id, name) VALUES (v_company_id, 'Arvagam') RETURNING id INTO v_brand_id;
  END IF;
  SELECT id INTO v_wh_id FROM warehouses WHERE company_id = v_company_id AND is_default = true LIMIT 1;
  IF v_wh_id IS NULL THEN
    INSERT INTO warehouses (company_id, name, is_default) VALUES (v_company_id, 'Default Warehouse', true);
  END IF;

  -- CASA_ARRA
  SELECT id INTO v_company_id FROM companies WHERE legal_name = 'Casa Arra' LIMIT 1;
  IF v_company_id IS NULL THEN
    INSERT INTO companies (legal_name, display_name) VALUES ('Casa Arra', 'CASA ARRA') RETURNING id INTO v_company_id;
  END IF;
  SELECT id INTO v_brand_id FROM brands WHERE company_id = v_company_id AND name = 'Kanjush' LIMIT 1;
  IF v_brand_id IS NULL THEN
    INSERT INTO brands (company_id, name) VALUES (v_company_id, 'Kanjush') RETURNING id INTO v_brand_id;
  END IF;
  SELECT id INTO v_wh_id FROM warehouses WHERE company_id = v_company_id AND is_default = true LIMIT 1;
  IF v_wh_id IS NULL THEN
    INSERT INTO warehouses (company_id, name, is_default) VALUES (v_company_id, 'Default Warehouse', true);
  END IF;

  -- UNASSIGNED
  SELECT id INTO v_company_id FROM companies WHERE legal_name = 'UNASSIGNED - NEEDS BRAND REVIEW' LIMIT 1;
  IF v_company_id IS NULL THEN
    INSERT INTO companies (legal_name, display_name) VALUES ('UNASSIGNED - NEEDS BRAND REVIEW', '⚠ UNASSIGNED - REVIEW') RETURNING id INTO v_company_id;
  END IF;
  SELECT id INTO v_brand_id FROM brands WHERE company_id = v_company_id AND name = 'Unassigned' LIMIT 1;
  IF v_brand_id IS NULL THEN
    INSERT INTO brands (company_id, name) VALUES (v_company_id, 'Unassigned') RETURNING id INTO v_brand_id;
  END IF;
  SELECT id INTO v_wh_id FROM warehouses WHERE company_id = v_company_id AND is_default = true LIMIT 1;
  IF v_wh_id IS NULL THEN
    INSERT INTO warehouses (company_id, name, is_default) VALUES (v_company_id, 'Default Warehouse', true);
  END IF;

END $$;

-- Ensure a marketplace_account exists per (brand, marketplace) this
-- import actually needs. Reuses ANY existing active account for that
-- brand+marketplace (regardless of label) so we never split one
-- brand's order history across two accounts; only creates a new
-- 'Bulk CSV Import' account when none exists at all.
DO $$
DECLARE
  v_company_id integer;
  v_brand_id integer;
  v_acct_id integer;
BEGIN
  -- ARVAGAM / AMAZON_IN
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Rugara' AND b.name='Arvagam' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'AMAZON_IN'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'AMAZON_IN'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- ARVAGAM / FLIPKART
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Rugara' AND b.name='Arvagam' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'FLIPKART'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'FLIPKART'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- ARVAGAM / MYNTRA
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Rugara' AND b.name='Arvagam' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'MYNTRA'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'MYNTRA'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- ARVAGAM / SNAPDEAL
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Rugara' AND b.name='Arvagam' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'SNAPDEAL'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'SNAPDEAL'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- KANJUSH / FLIPKART
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Casa Arra' AND b.name='Kanjush' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'FLIPKART'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'FLIPKART'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- KANJUSH / SNAPDEAL
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Casa Arra' AND b.name='Kanjush' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'SNAPDEAL'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'SNAPDEAL'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- UNASSIGNED / AMAZON_IN
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='UNASSIGNED - NEEDS BRAND REVIEW' AND b.name='Unassigned' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'AMAZON_IN'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'AMAZON_IN'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- UNASSIGNED / MEESHO
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='UNASSIGNED - NEEDS BRAND REVIEW' AND b.name='Unassigned' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'MEESHO'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'MEESHO'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- VARDHAMATI / AMAZON_IN
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Nyko Mart' AND b.name='Vardhamati' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'AMAZON_IN'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'AMAZON_IN'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- VARDHAMATI / FLIPKART
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Nyko Mart' AND b.name='Vardhamati' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'FLIPKART'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'FLIPKART'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

  -- VARDHAMATI / SNAPDEAL
  SELECT b.id, b.company_id INTO v_brand_id, v_company_id FROM brands b JOIN companies c ON c.id=b.company_id WHERE c.legal_name='Nyko Mart' AND b.name='Vardhamati' LIMIT 1;
  SELECT id INTO v_acct_id FROM marketplace_accounts WHERE brand_id = v_brand_id AND marketplace = 'SNAPDEAL'::marketplace AND is_active = true LIMIT 1;
  IF v_acct_id IS NULL THEN
    INSERT INTO marketplace_accounts (brand_id, marketplace, seller_account_label, credentials_encrypted)
    VALUES (v_brand_id, 'SNAPDEAL'::marketplace, 'Bulk CSV Import', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
  END IF;

END $$;

-- Seed the auto-assign memory with the 245 SKU codes this
-- run resolved with confidence (product title mentioned the brand,
-- and no other brand's title ever used the same code).
INSERT INTO import_brand_hints (marketplace_sku, brand_name, company_legal_name) VALUES
('HT-01-PURPLE-DUNG-XL', 'Vardhamati', 'Nyko Mart'),
('SVM-01-PINK SHIRT AND SHORT-M', 'Vardhamati', 'Nyko Mart'),
('SVM-12-BLACK PRINT TOP-3XL', 'Vardhamati', 'Nyko Mart'),
('SVM-01-PINK SHIRT AND SHORT-XL', 'Vardhamati', 'Nyko Mart'),
('SVM-06-YELLOW NIGHT SHORTS PRINTED-3XL', 'Vardhamati', 'Nyko Mart'),
('SVM-01-PINK SHIRT AND SHORT-3XL', 'Vardhamati', 'Nyko Mart'),
('SVM-12-BLACK PRINT TOP-M', 'Vardhamati', 'Nyko Mart'),
('SVM-02-PURPLE NIGHT SET DRESS-L', 'Vardhamati', 'Nyko Mart'),
('SVM-06-YELLOW NIGHT SHORTS PRINTED-XL', 'Vardhamati', 'Nyko Mart'),
('SVM-12-BLACK PRINT TOP-XXL', 'Vardhamati', 'Nyko Mart'),
('SVM-10-GREEN PRINT TOP-3XL', 'Vardhamati', 'Nyko Mart'),
('DRHT-03-YELLOW-DUNG-MHT-03-BLACK-DUNG-S', 'Vardhamati', 'Nyko Mart'),
('HT-13 MULTI-XXL', 'Vardhamati', 'Nyko Mart'),
('HT-13 MULTI-L', 'Vardhamati', 'Nyko Mart'),
('SVM-02-3XL', 'Kanjush', 'Casa Arra'),
('SVM-01-3XL', 'Kanjush', 'Casa Arra'),
('SVM-01-L', 'Kanjush', 'Casa Arra'),
('SVM-04-XL', 'Kanjush', 'Casa Arra'),
('SVM-02-M', 'Kanjush', 'Casa Arra'),
('SVM-02-L', 'Kanjush', 'Casa Arra'),
('SVM-03-L', 'Kanjush', 'Casa Arra'),
('SVM-06-L', 'Kanjush', 'Casa Arra'),
('A-SVM-01-3XL', 'Kanjush', 'Casa Arra'),
('SVM-01-XS', 'Kanjush', 'Casa Arra'),
('SVM-01-XL', 'Kanjush', 'Casa Arra'),
('SVM-02-XXL', 'Kanjush', 'Casa Arra'),
('SVM-02-XL', 'Kanjush', 'Casa Arra'),
('SVM-01-XXL', 'Kanjush', 'Casa Arra'),
('SVM-06-XXL', 'Kanjush', 'Casa Arra'),
('SVM-03-XL', 'Kanjush', 'Casa Arra'),
('SVM-02-S', 'Kanjush', 'Casa Arra'),
('A-SVM-01-XL', 'Kanjush', 'Casa Arra'),
('SVM-04-M', 'Kanjush', 'Casa Arra'),
('SVM-04-XXL', 'Kanjush', 'Casa Arra'),
('HT-12-XXL', 'Kanjush', 'Casa Arra'),
('SVM-01-S', 'Kanjush', 'Casa Arra'),
('SVM-03-3XL', 'Kanjush', 'Casa Arra'),
('SVM-01-M', 'Kanjush', 'Casa Arra'),
('SVM-04-S', 'Kanjush', 'Casa Arra'),
('SVM-04-XS', 'Kanjush', 'Casa Arra'),
('SVM-06-XL', 'Kanjush', 'Casa Arra'),
('SVM-06-3XL', 'Kanjush', 'Casa Arra'),
('SVM-06-S-M', 'Kanjush', 'Casa Arra'),
('SVM-15-3XL', 'Kanjush', 'Casa Arra'),
('SVM-03-S', 'Kanjush', 'Casa Arra'),
('SVM-07-3XL', 'Kanjush', 'Casa Arra'),
('SVM-08-L', 'Kanjush', 'Casa Arra'),
('SVM-09-3XL', 'Kanjush', 'Casa Arra'),
('SVM-08-S', 'Kanjush', 'Casa Arra'),
('SVM-17-L', 'Kanjush', 'Casa Arra'),
('HT-03-BLACK-DUNG-XXL', 'Arvagam', 'Rugara'),
('HT-BLUE-MT-XXL', 'Arvagam', 'Rugara'),
('HT-BLUE-MT-XL', 'Arvagam', 'Rugara'),
('HT-03-BLUE-DUNG-3XL', 'Arvagam', 'Rugara'),
('HT-03-BLUE-DUNG-XXL', 'Arvagam', 'Rugara'),
('SVM-11 GREY ANIMAL PRINT TOP-XXL', 'Arvagam', 'Rugara'),
('DUNGAREE PRINTED RED-L', 'Arvagam', 'Rugara'),
('NT-BLUE-XXL', 'Arvagam', 'Rugara'),
('NT-BLUE-M', 'Arvagam', 'Rugara'),
('PRUPLE DNGAREE-XS', 'Arvagam', 'Rugara'),
('HT 12 BLUE-M', 'Arvagam', 'Rugara'),
('KTHT-13-MULTI-PRINT-DRESS-XXL', 'Arvagam', 'Rugara'),
('KTHT-13-MULTI-PRINT-DRESS-3XL', 'Arvagam', 'Rugara'),
('DUNGAREE PRINTED RED-XXXL', 'Arvagam', 'Rugara'),
('NT-BLUE-XL', 'Arvagam', 'Rugara'),
('NT-BLUE-XS', 'Arvagam', 'Rugara'),
('NT-BLUE-L', 'Arvagam', 'Rugara'),
('HT 12 BLUE-S', 'Arvagam', 'Rugara'),
('KTHT-13-MULTI-PRINT-DRESS-XL', 'Arvagam', 'Rugara'),
('PRUPLE DNGAREE-M', 'Arvagam', 'Rugara'),
('KSVM-18-S', 'Kanjush', 'Casa Arra'),
('SVM-01-PINK SHIRT AND SHORTS-S', 'Vardhamati', 'Nyko Mart'),
('HT-01-PURPLE-DUNG-XXL', 'Vardhamati', 'Nyko Mart'),
('SVM-04-3XL', 'Kanjush', 'Casa Arra'),
('A-SVM-01-XXL', 'Kanjush', 'Casa Arra'),
('HT-03-YELLOW-DUNG-XL', 'Vardhamati', 'Nyko Mart'),
('HT 12 BLUE-3XL', 'Arvagam', 'Rugara'),
('SVM-07-XS', 'Kanjush', 'Casa Arra'),
('SVM-01-PINK SHIRT AND SHORT-XXL', 'Vardhamati', 'Nyko Mart'),
('HT 12 BLUE-XXL', 'Arvagam', 'Rugara'),
('A-SVM-01-M', 'Kanjush', 'Casa Arra'),
('HT 12 BLUE-L', 'Arvagam', 'Rugara'),
('A-SVM-01-S', 'Kanjush', 'Casa Arra'),
('DUNGAREE PRINTED RED-M', 'Arvagam', 'Rugara'),
('HT-12-L', 'Kanjush', 'Casa Arra'),
('DUNGAREE PRINTED RED -S', 'Arvagam', 'Rugara'),
('HT-01-PURPLE-DUNG-3XL', 'Vardhamati', 'Nyko Mart'),
('SVM-05-XS', 'Kanjush', 'Casa Arra'),
('SVM-04-L', 'Kanjush', 'Casa Arra'),
('SVM-17-XXL', 'Kanjush', 'Casa Arra'),
('A-SVM-01-L', 'Kanjush', 'Casa Arra'),
('SVM-14-3XL', 'Kanjush', 'Casa Arra'),
('SVM-16-3XL', 'Kanjush', 'Casa Arra'),
('HT 13 MULTI-XL', 'Arvagam', 'Rugara'),
('SVM-16-XL', 'Kanjush', 'Casa Arra'),
('HT 12 BLUE-XL', 'Arvagam', 'Rugara'),
('HT-03-RED-DUNG-3XL', 'Arvagam', 'Rugara'),
('HT-BLUE-MT-3XL', 'Arvagam', 'Rugara'),
('SVM-24-PINK-SRUGS-3XL', 'Arvagam', 'Rugara'),
('DUNGAREE PRINTED RED-XXL', 'Arvagam', 'Rugara'),
('SVM-05-M', 'Kanjush', 'Casa Arra'),
('SVM-10-3XL', 'Kanjush', 'Casa Arra'),
('HT-BLUE-MT-L', 'Arvagam', 'Rugara'),
('SVM-02-PURPALE FLORAL NIGHT SHORTS-S', 'Vardhamati', 'Nyko Mart'),
('SVM-23 GREEN KURTA-SET', 'Arvagam', 'Rugara'),
('SVM-02-PURPLE NIGHT SET DRESS-XXL', 'Vardhamati', 'Nyko Mart'),
('HT-19-ORANGE-GOWN MULTI C', 'Arvagam', 'Rugara'),
('SVM-22 BROW FLORAL GOWN', 'Vardhamati', 'Nyko Mart'),
('SVM-07-L', 'Kanjush', 'Casa Arra'),
('PRUPLE DNGAREE-XXXL', 'Arvagam', 'Rugara'),
('SVM-16-XXL', 'Kanjush', 'Casa Arra'),
('HT 13 MULTI-L', 'Arvagam', 'Rugara'),
('HT 13 MULTI-XXL', 'Arvagam', 'Rugara'),
('SVM-09-PINK-FLORAL TOP-M', 'Arvagam', 'Rugara'),
('HT-03-RED-DUNG-XL', 'Arvagam', 'Rugara'),
('HT-03-RED-DUNG-XXL', 'Arvagam', 'Rugara'),
('SVM-04-RED NIGHT SHORTS SET-L', 'Vardhamati', 'Nyko Mart'),
('SVM-22 BRO FLORAL GOWN', 'Vardhamati', 'Nyko Mart'),
('SVM-04-RED NIGHT SHORTS SET-3XL', 'Vardhamati', 'Nyko Mart'),
('HT-01-PURPLE-DUNG-S', 'Arvagam', 'Rugara'),
('PRUPLE DNGAREE-XL', 'Arvagam', 'Rugara'),
('KTHT-13-MULTI-PRINT-DRESS-M', 'Arvagam', 'Rugara'),
('SVM-02-PURPLE NIGHT SET DRESS-M', 'Kanjush', 'Casa Arra'),
('SVM-02-PURPLE NIGHT SET DRESS-3XL', 'Vardhamati', 'Nyko Mart'),
('HT-19-MULTI-COLOUR-FLAIRD DRESSES', 'Kanjush', 'Casa Arra'),
('SVM-14-XXL', 'Kanjush', 'Casa Arra'),
('SVM-02-PURPLE NIGHT SET DRESS-XL', 'Vardhamati', 'Nyko Mart'),
('SVM-10-GREEN GEOMETIC TOP-XL', 'Arvagam', 'Rugara'),
('PRUPLE DNGAREE-L', 'Arvagam', 'Rugara'),
('HT 13 MULTI-M', 'Arvagam', 'Rugara'),
('KTHT-13-MULTI-PRINT-DRESS-L', 'Arvagam', 'Rugara'),
('SVM-05-SKY BLUE NIGHT SHORT-L', 'Vardhamati', 'Nyko Mart'),
('BLU TITAR-L', 'Kanjush', 'Casa Arra'),
('RS-2 GREEN COLOUR FLORAL TOP-XXL', 'Kanjush', 'Casa Arra'),
('HT-03-YELLOW-DUNG-M', 'Arvagam', 'Rugara'),
('SVM-10-GREEN GEOMETIC TOP-S', 'Arvagam', 'Rugara'),
('SVM-09-PINK TOP-XL', 'Vardhamati', 'Nyko Mart'),
('SVM-05-SKY BLUE NIGHT SHORT-3XL', 'Vardhamati', 'Nyko Mart'),
('SVM-05-SKY BLUE NIGHT SHORT-XXL', 'Vardhamati', 'Nyko Mart'),
('SVM-04-RED NIGHT SHORTS SET-XL', 'Vardhamati', 'Nyko Mart'),
('RS-4-XXL', 'Kanjush', 'Casa Arra'),
('SVM-04-RED NIGHT SHORTS SET-M', 'Vardhamati', 'Nyko Mart'),
('HT 13 MULTI-3XL', 'Arvagam', 'Rugara'),
('HT-RED-MT-XL', 'Arvagam', 'Rugara'),
('RAS-4 PINK TANK-TOP-S', 'Arvagam', 'Rugara'),
('HT-RED-MT_XL', 'Arvagam', 'Rugara'),
('HT-PURP-SD_XXL', 'Arvagam', 'Rugara'),
('NT-601-XL', 'Vardhamati', 'Nyko Mart'),
('NT-601-M', 'Vardhamati', 'Nyko Mart'),
('NT-601-S', 'Vardhamati', 'Nyko Mart'),
('NT-604-S', 'Vardhamati', 'Nyko Mart'),
('NT-601-L', 'Vardhamati', 'Nyko Mart'),
('NT-601-XXL', 'Vardhamati', 'Nyko Mart'),
('HT-03 BLACK DANGAREE', 'Vardhamati', 'Nyko Mart'),
('HT-05-RED_M', 'Vardhamati', 'Nyko Mart'),
('NT-601-XXS', 'Vardhamati', 'Nyko Mart'),
('HT-05-BLACK_XXL', 'Vardhamati', 'Nyko Mart'),
('NT-602-S', 'Vardhamati', 'Nyko Mart'),
('HT-08-PURPLE-SOLID-L', 'Arvagam', 'Rugara'),
('NT-604-XL', 'Vardhamati', 'Nyko Mart'),
('NT-602-M', 'Vardhamati', 'Nyko Mart'),
('NT-604-XXL', 'Vardhamati', 'Nyko Mart'),
('HT-03-RED_XXL', 'Vardhamati', 'Nyko Mart'),
('HT-05-BLACK_S', 'Vardhamati', 'Nyko Mart'),
('HT-05-BLACK_XL', 'Vardhamati', 'Nyko Mart'),
('N_HT-13-MULTI-PRINTED_XXL', 'Kanjush', 'Casa Arra'),
('KU_HT-03-BLUE -DUNG_L', 'Kanjush', 'Casa Arra'),
('K_HT-03-PURPLE DUNGAREE_M', 'Kanjush', 'Casa Arra'),
('KU_HT-03-BLUE -DUNG_XXXL', 'Kanjush', 'Casa Arra'),
('KU_HT-03-BLUE -DUNG_XL', 'Kanjush', 'Casa Arra'),
('KU_HT-03-BLUE -DUNG_S', 'Kanjush', 'Casa Arra'),
('J_HT-03-RED-DUNG_L', 'Kanjush', 'Casa Arra'),
('KU_HT-03-BLUE -DUNG_XS', 'Kanjush', 'Casa Arra'),
('KU_HT-03-BLUE -DUNG_M', 'Kanjush', 'Casa Arra'),
('K_HT-03-BLACK-DUNG_XXXL', 'Kanjush', 'Casa Arra'),
('K_HT-03-PURPLE DUNGAREE_L', 'Kanjush', 'Casa Arra'),
('N_HT-13-MULTI-PRINTED_XXXL', 'Kanjush', 'Casa Arra'),
('KU_HT-03-BLUE -DUNG_XXL', 'Kanjush', 'Casa Arra'),
('N_HT-13-MULTI-PRINTED_XL', 'Kanjush', 'Casa Arra'),
('HT-RED-MT-PT_L', 'Arvagam', 'Rugara'),
('HT-05-BLACK_M', 'Vardhamati', 'Nyko Mart'),
('K_HT-03-PURPLE DUNGAREE_S', 'Kanjush', 'Casa Arra'),
('A_HT-14-RED-PRINT-DUNG_L', 'Kanjush', 'Casa Arra'),
('SKUCODE', 'Arvagam', 'Rugara'),
('HT-07-RED_S', 'Arvagam', 'Rugara'),
('HT-03 RED DUNG-L', 'Kanjush', 'Casa Arra'),
('J_HT-03-RED-DUNG_XXXL', 'Kanjush', 'Casa Arra'),
('HT-11-RED-PRINT-MATENITY_XL', 'Kanjush', 'Casa Arra'),
('HT-05-RED_S', 'Vardhamati', 'Nyko Mart'),
('A_HT-14-RED-PRINT-DUNG_XXXL', 'Kanjush', 'Casa Arra'),
('HT-05-BLACK PRINT DUNG-3XL', 'Kanjush', 'Casa Arra'),
('N_HT-13-MULTI-PRINTED_L', 'Kanjush', 'Casa Arra'),
('J_HT-03-RED-DUNG_XXL', 'Kanjush', 'Casa Arra'),
('HT-06-BLUE_S', 'Arvagam', 'Rugara'),
('HT-10-BLUE-SOLID-MAT-3XL', 'Kanjush', 'Casa Arra'),
('NT-603-M', 'Vardhamati', 'Nyko Mart'),
('NT-604-M', 'Vardhamati', 'Nyko Mart'),
('SVM-11-3XL', 'Vardhamati', 'Nyko Mart'),
('HT-RED-MT-PT_XXXL', 'Arvagam', 'Rugara'),
('HT-03-RED_XL', 'Vardhamati', 'Nyko Mart'),
('N_HT-13-MULTI-PRINTED_M', 'Kanjush', 'Casa Arra'),
('SVM-08-XS', 'Vardhamati', 'Nyko Mart'),
('K_HT-03-PURPLE DUNGAREE_XL', 'Kanjush', 'Casa Arra'),
('HT-RED-MT_S', 'Arvagam', 'Rugara'),
('NT-603-XL', 'Vardhamati', 'Nyko Mart'),
('SVM-23 KURTA WITH PANT-XL', 'Arvagam', 'Rugara'),
('SVM-23 KURTA WITH PANT-3XL', 'Arvagam', 'Rugara'),
('SVM-08-3XL', 'Vardhamati', 'Nyko Mart'),
('K_HT-03-PURPLE DUNGAREE_XXXL', 'Kanjush', 'Casa Arra'),
('A_HT-14-RED-PRINT-DUNG_S', 'Kanjush', 'Casa Arra'),
('SVM-23 KURTA WITH PANT-L', 'Arvagam', 'Rugara'),
('HT-RED-SD_S', 'Vardhamati', 'Nyko Mart'),
('SVM-23 KURTA WITH PANT-M', 'Arvagam', 'Rugara'),
('SVM-23 KURTA WITH PANT-XXL', 'Arvagam', 'Rugara'),
('SVM-23 KURTA WITH PANT-S', 'Arvagam', 'Rugara'),
('HT-RED-MT-PT_S', 'Arvagam', 'Rugara'),
('NT-601-XS', 'Vardhamati', 'Nyko Mart'),
('NT-604-XS', 'Vardhamati', 'Nyko Mart'),
('NT-602-XXL', 'Vardhamati', 'Nyko Mart'),
('NT-64-S', 'Kanjush', 'Casa Arra'),
('HT-03-RED_L', 'Vardhamati', 'Nyko Mart'),
('HT-03-RED_M', 'Vardhamati', 'Nyko Mart'),
('SVM-24 PINK FLORAL SRUGS-3XL', 'Vardhamati', 'Nyko Mart'),
('SVM-24 PINK FLORAL SRUGS-L', 'Vardhamati', 'Nyko Mart'),
('SVM-24 PINK FLORAL SRUGS-M', 'Vardhamati', 'Nyko Mart'),
('K_HT-03-PURPLE DUNGAREE_XXL', 'Kanjush', 'Casa Arra'),
('SVM-24 PINK FLORAL SRUGS-2XL', 'Vardhamati', 'Nyko Mart'),
('SVM-24 PINK FLORAL SRUGS-XL', 'Vardhamati', 'Nyko Mart'),
('SVM-24 PINK FLORAL SRUGS-S', 'Vardhamati', 'Nyko Mart'),
('HT-03-RED_S', 'Vardhamati', 'Nyko Mart'),
('SVM-11-XL', 'Vardhamati', 'Nyko Mart'),
('HT-03-RED-XXL', 'Arvagam', 'Rugara'),
('HT-05-RED-XL', 'Arvagam', 'Rugara'),
('HT-03-BLUE-S', 'Arvagam', 'Rugara'),
('HT-03-BLACK-XXL', 'Arvagam', 'Rugara'),
('HT-13-XL', 'Arvagam', 'Rugara'),
('HT-03-YELLOW-L', 'Arvagam', 'Rugara'),
('HT-03-BLUE-3XL', 'Arvagam', 'Rugara'),
('HT-03-BLACK-M', 'Arvagam', 'Rugara'),
('HT-03-RED-XL', 'Arvagam', 'Rugara'),
('HT-05-BLACK-3XL', 'Arvagam', 'Rugara'),
('HT-03-YELLOW-XXL', 'Arvagam', 'Rugara'),
('HT-03-BLUE-XL', 'Arvagam', 'Rugara'),
('HT-05-RED-S', 'Arvagam', 'Rugara'),
('HT-03-BLUE-XXL', 'Arvagam', 'Rugara')
ON CONFLICT (marketplace_sku, brand_name) DO NOTHING;

-- Staging tables. PERSISTENT (not TEMP) because each numbered file in
-- this folder is run as a separate SQL editor submission/connection --
-- a TEMP table would vanish before the next file runs. Prefixed and
-- harmless to leave in place; 99_finalize.sql has an optional DROP.
CREATE TABLE IF NOT EXISTS _import_stg_orders (
  marketplace varchar(20), marketplace_order_id text, brand_key text, status text, fulfillment_type text,
  invoice_number text, invoice_date timestamptz, ordered_at timestamptz, verified_at timestamptz, raw_json text
);
CREATE TABLE IF NOT EXISTS _import_stg_items (
  marketplace varchar(20), marketplace_order_id text, line_id text, marketplace_sku text, product_title text,
  variant_size text, quantity integer, unit_price numeric, mrp numeric, shipping_charge numeric,
  invoice_amount numeric, cgst numeric, sgst numeric, igst numeric, tax_rate numeric, hsn text, settlement_est numeric
);
CREATE TABLE IF NOT EXISTS _import_stg_shipments (
  marketplace varchar(20), marketplace_order_id text, shipment_id text, package_id text, packet_id text,
  awb_number text, carrier text, tracking_url text, service_level text, recipient_name text,
  recipient_address1 text, recipient_address2 text, recipient_city text, recipient_state text, recipient_pincode text,
  dispatch_start timestamptz, dispatch_end timestamptz, shipped_at timestamptz, delivered_at timestamptz,
  pkg_length numeric, pkg_breadth numeric, pkg_height numeric, pkg_weight numeric
);
CREATE TABLE IF NOT EXISTS _import_stg_returns (
  marketplace varchar(20), marketplace_order_id text, status text, return_type text, reason text
);
-- Clear out any partial data from a previous attempt so re-running
-- this whole file sequence from 00 never double-stages rows.
TRUNCATE _import_stg_orders, _import_stg_items, _import_stg_shipments, _import_stg_returns;

COMMIT;
